# Site
name: "canonmj"
title: "canonmj"
description: "ë””ìì´ë„ˆì—ì„œ ê°œë°œìë¡œ, Canonì˜ ì¼ìƒê³¼ ì½”ë”©ì—¬ì •ğŸš€"
logo: "assets/images/mj.png"
favicon: "assets/images/mj-icon.png"
baseurl:
google_analytics: "UA-xxxxxxxx-1"
disqus: "demowebsite"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
email: canon.minjoo@gmail.com

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: "assets/images/avatar-sal.png"
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  minjoo:
    name: minjoo
    display_name: minjoo
    avatar: "assets/images/mj2.jpeg"
    email: canon.minjoo@gmail.com
    web: canonmj.github.io
    twitter:
    description: "ì¢‹ì€ ì‚¬ìš©ì„±, ë¯¸ë‹ˆë©€ë¦¬ì¦˜ì„ ì¢‹ì•„í•˜ê³  ê°€ë” ì‘ì€ê²ƒì—ë„ ë§ì´ ì§‘ì°©í•©ë‹ˆë‹¤."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
